from __future__ import annotations

from optimize_ce_zlsma_kama_rule import RuleParams

# ---------------------------------------------------------------------------
# V3 best parameters — top-Sharpe row from each symbol's para.csv
# ---------------------------------------------------------------------------

V3_BEST_PARAMS: dict[str, RuleParams] = {
    # SPY: Sharpe 6.82, Return 32.8%, Win 74.7%, 1203 trades, DD -0.60%
    "SPY": RuleParams(
        ce_length=1,
        ce_multiplier=2.0,
        trend_mode="price_above_both",
        tp_atr_multiple=0.5,
        sl_atr_multiple=0.0,
        session_filter="before_1230",
        exit_model="atr_tp_pct_sl",
        tp_pct=0.0,
        sl_pct=0.002,
        zlsma_length=40,
        zlsma_offset=0,
        kama_er_length=11,
        kama_fast_length=2,
        kama_slow_length=40,
        confirmation_mode="none",
        zlsma_slope_threshold=0.0002,
        atr_percentile_lookback=60,
        atr_percentile_min=0.0,
        pseudo_cvd_method="clv_body_volume",
        cvd_lookback=20,
        cvd_slope_lookback=3,
        cvd_classic_divergence=True,
        cvd_slope_divergence=True,
        time_stop_minutes=10,
        force_time_stop=True,
        time_progress_threshold=0.5,
        profit_lock_trigger_pct=0.0,
        profit_lock_fraction=0.0,
        pa_or_filter=False,
        pa_or_wide_tp_scale=0.7,
        pa_require_signal_bar=True,
        pa_require_h2_l2=False,
        pa_pressure_min=0.0,
        pa_use_mm_target=False,
        pa_use_pa_stops=False,
        pa_mag_bar_exit=False,
        pa_exhaustion_gap_exit=False,
        pa_regime_filter=False,
        pa_20bar_neutral=False,
        pa_ii_breakout_entry=False,
        pa_position_sizing_mode="fixed",
    ),
    # QQQ: Sharpe 7.04, Return 42.2%, Win 64.9%, 906 trades, DD -1.04%
    "QQQ": RuleParams(
        ce_length=2,
        ce_multiplier=2.5,
        trend_mode="price_above_both",
        tp_atr_multiple=0.0,
        sl_atr_multiple=0.0,
        session_filter="before_1230",
        exit_model="pct",
        tp_pct=0.0015,
        sl_pct=0.001,
        zlsma_length=45,
        zlsma_offset=0,
        kama_er_length=11,
        kama_fast_length=2,
        kama_slow_length=30,
        confirmation_mode="none",
        zlsma_slope_threshold=0.0002,
        atr_percentile_lookback=60,
        atr_percentile_min=0.0,
        pseudo_cvd_method="clv_body_volume",
        cvd_lookback=20,
        cvd_slope_lookback=3,
        cvd_classic_divergence=True,
        cvd_slope_divergence=True,
        time_stop_minutes=15,
        force_time_stop=True,
        time_progress_threshold=0.5,
        profit_lock_trigger_pct=0.0,
        profit_lock_fraction=0.0,
        pa_or_filter=False,
        pa_or_wide_tp_scale=0.7,
        pa_require_signal_bar=True,
        pa_require_h2_l2=False,
        pa_pressure_min=0.0,
        pa_use_mm_target=False,
        pa_use_pa_stops=True,
        pa_mag_bar_exit=False,
        pa_exhaustion_gap_exit=False,
        pa_regime_filter=True,
        pa_20bar_neutral=False,
        pa_ii_breakout_entry=False,
        pa_position_sizing_mode="risk_based",
    ),
}

# ---------------------------------------------------------------------------
# V3 backtest performance benchmarks (for deviation monitoring)
# ---------------------------------------------------------------------------

V3_BENCHMARKS: dict[str, dict[str, float]] = {
    "SPY": {
        "sharpe": 6.82,
        "win_rate": 0.747,
        "max_drawdown": -0.006,
        "avg_holding_minutes": 5.2,
        "total_return": 0.328,
        "trade_count": 1203,
        "take_profit_rate": 0.639,
        "stop_loss_rate": 0.036,
        "time_stop_rate": 0.325,
    },
    "QQQ": {
        "sharpe": 7.04,
        "win_rate": 0.649,
        "max_drawdown": -0.010,
        "avg_holding_minutes": 10.3,
        "total_return": 0.422,
        "trade_count": 906,
        "take_profit_rate": 0.499,
        "stop_loss_rate": 0.074,
        "time_stop_rate": 0.427,
    },
}
